cloud:
  aws:
    credentials:
      access-key: AKIARGBRHWTNC53UE7XX
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: travellerstorage


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 20MB

server:
  port: 9090